modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="nompes_legendary_weapons"
version="1.0.0"
displayName="Nompe's Legendary Weapons"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="AlexNompe, MCreator"

[[dependencies.nompes_legendary_weapons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




